### ISSUE TITLE
Interface not available in the source code

### ISSUE THREAD

**Issue by GirodFred** [larshp/gantt#8]
Hi,

I am trying to implement your source code in my system, but it seems objects are missing. Especially the interfaces. 
Do you have an update of your source code ?

Thanks
Fred

**Comment by larshp** [comment]
feel free to try it out, but the code is quite old, not finished, and not maintained.

What is the name of the missing objects?

As far as I remember, there is a dependency to https://github.com/larshp/ABAP-Swagger which must also be installed

**Comment by GirodFred** [comment]
It miss exactly the dependency on ABAP Swagger, I will install it. 
I would like to make a test to see the layout. For the moment only the part of the Creation test program is working.

**Comment by larshp** [comment]
Pull requests are welcome if you choose to do some changes, or wish to add clarifications in the repository
